// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: github.com/loomnetwork/zombie_battleground/types/zb/zb.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from github.com/loomnetwork/zombie_battleground/types/zb/zb.proto</summary>
public static partial class ZbReflection {

  #region Descriptor
  /// <summary>File descriptor for github.com/loomnetwork/zombie_battleground/types/zb/zb.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ZbReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CjxnaXRodWIuY29tL2xvb21uZXR3b3JrL3pvbWJpZV9iYXR0bGVncm91bmQv",
          "dHlwZXMvemIvemIucHJvdG8ihgIKB0FjY291bnQSCgoCaWQYASABKAkSEAoI",
          "dXNlcm5hbWUYAiABKAkSGwoTcHJpdmF0ZV9rZXlfY3JlYXRlZBgDIAEoCBId",
          "ChVwaG9uZV9udW1iZXJfdmVyaWZpZWQYBCABKAgSFwoPcmV3YXJkX3JlZGVl",
          "bWVkGAUgASgIEhYKDmlzX2tpY2tzdGFydGVyGAYgASgIEg0KBWltYWdlGAcg",
          "ASgJEhoKEmVtYWlsX25vdGlmaWNhdGlvbhgIIAEoCBIRCgllbG9fc2NvcmUY",
          "CSABKAMSFAoMY3VycmVudF90aWVyGAogASgFEhwKFGdhbWVfbWVtYmVyc2hp",
          "cF90aWVyGAsgASgFIigKFENyZWF0ZUFjY291bnRSZXF1ZXN0EhAKCHVzZXJu",
          "YW1lGAEgASgJIjcKFFVwZGF0ZUFjY291bnRSZXF1ZXN0EhAKCHVzZXJuYW1l",
          "GAEgASgJEg0KBWltYWdlGAIgASgJYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Account), global::Account.Parser, new[]{ "Id", "Username", "PrivateKeyCreated", "PhoneNumberVerified", "RewardRedeemed", "IsKickstarter", "Image", "EmailNotification", "EloScore", "CurrentTier", "GameMembershipTier" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::CreateAccountRequest), global::CreateAccountRequest.Parser, new[]{ "Username" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::UpdateAccountRequest), global::UpdateAccountRequest.Parser, new[]{ "Username", "Image" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Account : pb::IMessage<Account> {
  private static readonly pb::MessageParser<Account> _parser = new pb::MessageParser<Account>(() => new Account());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Account> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ZbReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Account() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Account(Account other) : this() {
    id_ = other.id_;
    username_ = other.username_;
    privateKeyCreated_ = other.privateKeyCreated_;
    phoneNumberVerified_ = other.phoneNumberVerified_;
    rewardRedeemed_ = other.rewardRedeemed_;
    isKickstarter_ = other.isKickstarter_;
    image_ = other.image_;
    emailNotification_ = other.emailNotification_;
    eloScore_ = other.eloScore_;
    currentTier_ = other.currentTier_;
    gameMembershipTier_ = other.gameMembershipTier_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Account Clone() {
    return new Account(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private string id_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Id {
    get { return id_; }
    set {
      id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "username" field.</summary>
  public const int UsernameFieldNumber = 2;
  private string username_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Username {
    get { return username_; }
    set {
      username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "private_key_created" field.</summary>
  public const int PrivateKeyCreatedFieldNumber = 3;
  private bool privateKeyCreated_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool PrivateKeyCreated {
    get { return privateKeyCreated_; }
    set {
      privateKeyCreated_ = value;
    }
  }

  /// <summary>Field number for the "phone_number_verified" field.</summary>
  public const int PhoneNumberVerifiedFieldNumber = 4;
  private bool phoneNumberVerified_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool PhoneNumberVerified {
    get { return phoneNumberVerified_; }
    set {
      phoneNumberVerified_ = value;
    }
  }

  /// <summary>Field number for the "reward_redeemed" field.</summary>
  public const int RewardRedeemedFieldNumber = 5;
  private bool rewardRedeemed_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool RewardRedeemed {
    get { return rewardRedeemed_; }
    set {
      rewardRedeemed_ = value;
    }
  }

  /// <summary>Field number for the "is_kickstarter" field.</summary>
  public const int IsKickstarterFieldNumber = 6;
  private bool isKickstarter_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool IsKickstarter {
    get { return isKickstarter_; }
    set {
      isKickstarter_ = value;
    }
  }

  /// <summary>Field number for the "image" field.</summary>
  public const int ImageFieldNumber = 7;
  private string image_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Image {
    get { return image_; }
    set {
      image_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "email_notification" field.</summary>
  public const int EmailNotificationFieldNumber = 8;
  private bool emailNotification_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool EmailNotification {
    get { return emailNotification_; }
    set {
      emailNotification_ = value;
    }
  }

  /// <summary>Field number for the "elo_score" field.</summary>
  public const int EloScoreFieldNumber = 9;
  private long eloScore_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long EloScore {
    get { return eloScore_; }
    set {
      eloScore_ = value;
    }
  }

  /// <summary>Field number for the "current_tier" field.</summary>
  public const int CurrentTierFieldNumber = 10;
  private int currentTier_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CurrentTier {
    get { return currentTier_; }
    set {
      currentTier_ = value;
    }
  }

  /// <summary>Field number for the "game_membership_tier" field.</summary>
  public const int GameMembershipTierFieldNumber = 11;
  private int gameMembershipTier_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int GameMembershipTier {
    get { return gameMembershipTier_; }
    set {
      gameMembershipTier_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Account);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Account other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Username != other.Username) return false;
    if (PrivateKeyCreated != other.PrivateKeyCreated) return false;
    if (PhoneNumberVerified != other.PhoneNumberVerified) return false;
    if (RewardRedeemed != other.RewardRedeemed) return false;
    if (IsKickstarter != other.IsKickstarter) return false;
    if (Image != other.Image) return false;
    if (EmailNotification != other.EmailNotification) return false;
    if (EloScore != other.EloScore) return false;
    if (CurrentTier != other.CurrentTier) return false;
    if (GameMembershipTier != other.GameMembershipTier) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Id.Length != 0) hash ^= Id.GetHashCode();
    if (Username.Length != 0) hash ^= Username.GetHashCode();
    if (PrivateKeyCreated != false) hash ^= PrivateKeyCreated.GetHashCode();
    if (PhoneNumberVerified != false) hash ^= PhoneNumberVerified.GetHashCode();
    if (RewardRedeemed != false) hash ^= RewardRedeemed.GetHashCode();
    if (IsKickstarter != false) hash ^= IsKickstarter.GetHashCode();
    if (Image.Length != 0) hash ^= Image.GetHashCode();
    if (EmailNotification != false) hash ^= EmailNotification.GetHashCode();
    if (EloScore != 0L) hash ^= EloScore.GetHashCode();
    if (CurrentTier != 0) hash ^= CurrentTier.GetHashCode();
    if (GameMembershipTier != 0) hash ^= GameMembershipTier.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Id.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Id);
    }
    if (Username.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Username);
    }
    if (PrivateKeyCreated != false) {
      output.WriteRawTag(24);
      output.WriteBool(PrivateKeyCreated);
    }
    if (PhoneNumberVerified != false) {
      output.WriteRawTag(32);
      output.WriteBool(PhoneNumberVerified);
    }
    if (RewardRedeemed != false) {
      output.WriteRawTag(40);
      output.WriteBool(RewardRedeemed);
    }
    if (IsKickstarter != false) {
      output.WriteRawTag(48);
      output.WriteBool(IsKickstarter);
    }
    if (Image.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Image);
    }
    if (EmailNotification != false) {
      output.WriteRawTag(64);
      output.WriteBool(EmailNotification);
    }
    if (EloScore != 0L) {
      output.WriteRawTag(72);
      output.WriteInt64(EloScore);
    }
    if (CurrentTier != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(CurrentTier);
    }
    if (GameMembershipTier != 0) {
      output.WriteRawTag(88);
      output.WriteInt32(GameMembershipTier);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Id.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
    }
    if (Username.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
    }
    if (PrivateKeyCreated != false) {
      size += 1 + 1;
    }
    if (PhoneNumberVerified != false) {
      size += 1 + 1;
    }
    if (RewardRedeemed != false) {
      size += 1 + 1;
    }
    if (IsKickstarter != false) {
      size += 1 + 1;
    }
    if (Image.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Image);
    }
    if (EmailNotification != false) {
      size += 1 + 1;
    }
    if (EloScore != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(EloScore);
    }
    if (CurrentTier != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurrentTier);
    }
    if (GameMembershipTier != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(GameMembershipTier);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Account other) {
    if (other == null) {
      return;
    }
    if (other.Id.Length != 0) {
      Id = other.Id;
    }
    if (other.Username.Length != 0) {
      Username = other.Username;
    }
    if (other.PrivateKeyCreated != false) {
      PrivateKeyCreated = other.PrivateKeyCreated;
    }
    if (other.PhoneNumberVerified != false) {
      PhoneNumberVerified = other.PhoneNumberVerified;
    }
    if (other.RewardRedeemed != false) {
      RewardRedeemed = other.RewardRedeemed;
    }
    if (other.IsKickstarter != false) {
      IsKickstarter = other.IsKickstarter;
    }
    if (other.Image.Length != 0) {
      Image = other.Image;
    }
    if (other.EmailNotification != false) {
      EmailNotification = other.EmailNotification;
    }
    if (other.EloScore != 0L) {
      EloScore = other.EloScore;
    }
    if (other.CurrentTier != 0) {
      CurrentTier = other.CurrentTier;
    }
    if (other.GameMembershipTier != 0) {
      GameMembershipTier = other.GameMembershipTier;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Id = input.ReadString();
          break;
        }
        case 18: {
          Username = input.ReadString();
          break;
        }
        case 24: {
          PrivateKeyCreated = input.ReadBool();
          break;
        }
        case 32: {
          PhoneNumberVerified = input.ReadBool();
          break;
        }
        case 40: {
          RewardRedeemed = input.ReadBool();
          break;
        }
        case 48: {
          IsKickstarter = input.ReadBool();
          break;
        }
        case 58: {
          Image = input.ReadString();
          break;
        }
        case 64: {
          EmailNotification = input.ReadBool();
          break;
        }
        case 72: {
          EloScore = input.ReadInt64();
          break;
        }
        case 80: {
          CurrentTier = input.ReadInt32();
          break;
        }
        case 88: {
          GameMembershipTier = input.ReadInt32();
          break;
        }
      }
    }
  }

}

public sealed partial class CreateAccountRequest : pb::IMessage<CreateAccountRequest> {
  private static readonly pb::MessageParser<CreateAccountRequest> _parser = new pb::MessageParser<CreateAccountRequest>(() => new CreateAccountRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<CreateAccountRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ZbReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public CreateAccountRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public CreateAccountRequest(CreateAccountRequest other) : this() {
    username_ = other.username_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public CreateAccountRequest Clone() {
    return new CreateAccountRequest(this);
  }

  /// <summary>Field number for the "username" field.</summary>
  public const int UsernameFieldNumber = 1;
  private string username_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Username {
    get { return username_; }
    set {
      username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as CreateAccountRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(CreateAccountRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Username != other.Username) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Username.Length != 0) hash ^= Username.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Username.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Username);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Username.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(CreateAccountRequest other) {
    if (other == null) {
      return;
    }
    if (other.Username.Length != 0) {
      Username = other.Username;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Username = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class UpdateAccountRequest : pb::IMessage<UpdateAccountRequest> {
  private static readonly pb::MessageParser<UpdateAccountRequest> _parser = new pb::MessageParser<UpdateAccountRequest>(() => new UpdateAccountRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<UpdateAccountRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ZbReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public UpdateAccountRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public UpdateAccountRequest(UpdateAccountRequest other) : this() {
    username_ = other.username_;
    image_ = other.image_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public UpdateAccountRequest Clone() {
    return new UpdateAccountRequest(this);
  }

  /// <summary>Field number for the "username" field.</summary>
  public const int UsernameFieldNumber = 1;
  private string username_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Username {
    get { return username_; }
    set {
      username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "image" field.</summary>
  public const int ImageFieldNumber = 2;
  private string image_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Image {
    get { return image_; }
    set {
      image_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as UpdateAccountRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(UpdateAccountRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Username != other.Username) return false;
    if (Image != other.Image) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Username.Length != 0) hash ^= Username.GetHashCode();
    if (Image.Length != 0) hash ^= Image.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Username.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Username);
    }
    if (Image.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Image);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Username.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
    }
    if (Image.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Image);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(UpdateAccountRequest other) {
    if (other == null) {
      return;
    }
    if (other.Username.Length != 0) {
      Username = other.Username;
    }
    if (other.Image.Length != 0) {
      Image = other.Image;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Username = input.ReadString();
          break;
        }
        case 18: {
          Image = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
