

public enum LocalizationKeys
{
    LoadingText,
    PressAnyKeyText,
    PlayText,
    ShopText,
    OpenPacksText,
    ArmyText,
    SettingsText,
    VideoText,
    AudioText,
    ResolutionText,
    SfxVolumeText,
    ScreenModeText,
    FullScreenText,
    MusicVolumeText,
    QuitToDesktopText,
    QuitToMainMenuText,
    ZombieArmyText,
    OpenText,
    BuyText,
    TutorialText,
    SoloText,
    VsText,
    CustomModeText,
    CasualText,
    RankedText,
    FriendlyText,
    ChooseHordeText,
    NewHordeText,
    BattleText,
    SaveText
}
